name: CI

on:
  push:
    branches:
      - master
      - NR-427782
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'npm'

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Run Frontend Tests
        run: npm run test:ci

      - name: Build Frontend
        run: npm run build  

      - name: Setup Go Environment
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "go.sum" 

      - name: Test Backend
        uses: magefile/mage-action@v3
        with:
          version: latest
          args: coverage

      - name: Build Backend
        run: |
            # Create dist directory if it doesn't exist
            mkdir -p dist
            
            # Get current OS and architecture
            OS=$(go env GOOS)
            ARCH=$(go env GOARCH)
            
            echo "Building for current system: $OS-$ARCH..."
            
            # Build for current OS and architecture
            go build -o dist/gpx_newrelic_grafana_plugin_${OS}_${ARCH} ./pkg
            
            # Build manifest file
            echo "Building manifest..."
            go build -o dist/go_plugin_build_manifest ./pkg
            
            # List the built files
            echo "Built files:"
            ls -la dist/
